apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./karpenter.k8s.aws_ec2nodeclasses.yaml
  - ./karpenter.sh_nodeclaims.yaml
  - ./karpenter.sh_nodepools.yaml

labels:
  - pairs:
      application.giantswarm.io/team: "phoenix"
      giantswarm.io/service-type: "managed"
    includeTemplates: true

patches:
  - target:
      kind: CustomResourceDefinition
    patch: |-
      - op: add
        path: /metadata/annotations/helm.sh~1resource-policy
        value: keep
