apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
  - path: vendor
    contents:
      - path: karpenter-provider-aws-upstream
        git:
          url: https://github.com/giantswarm/karpenter-provider-aws-upstream
          ref: "main"
        includePaths:
          - charts/karpenter/templates/**/*
          - pkg/apis/crds/**/*.yaml
  - path: helm/karpenter/templates
    contents:
      - path: .
        directory:
          path: vendor/karpenter-provider-aws-upstream/charts/karpenter/templates
