kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.name }}
  labels:
    {{- include "karpenter.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "karpenter.selectorLabels" . | nindent 6 }}
  ingress:
  - ports:
    - port: {{ .Values.controller.metrics.port }}
      protocol: TCP
    - port: {{ .Values.controller.healthProbe.port }}
      protocol: TCP
    - port: {{ .Values.webhook.port }}
      protocol: TCP
  egress:
  - {}
  policyTypes:
  - Egress
  - Ingress
