# ─── UPSTREAM ────────────────────────────────────────────────────────────────
upstream:
  nameOverride: karpenter

# ─── EXTRAS ──────────────────────────────────────────────────────────────────
podLogs:
  enabled: false
  tenant: ""

global:
  podSecurityStandards:
    enforced: false
